[google]
client_id = "145117178529-7lsegp50spfq1691duq4e1k0cb6413t3.apps.googleusercontent.com"
project_id = "plugin-453501"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_secret = "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"

redirect_uris = [
  "http://localhost:8501/",
  "http://localhost:8502",
  "http://localhost:49501/",
  "http://localhost/"
]
